#!/usr/bin/python3
#
# rcl -- Routesia command line interface
#

from routesia.cli.cli import CLI
from routesia.config.commands import ConfigCommandSet


if __name__ == '__main__':
    cli = CLI()
    cli.register_command_set(ConfigCommandSet)
    cli.run()
